---
resource_types:
- name: maven
  type: registry-image
  source:
    repository: nulldriver/maven-resource
    tag: latest

resources:
- name: ci-utils
  type: git
  source:
    uri: https://github.com/making/ci-utils.git
    branch: master
- name: concourse
  type: github-release
  check_every: 30m
  source:
    owner: concourse
    repository: concourse
    access_token: ((github-access-token))
- name: cfcr
  type: github-release
  check_every: 30m
  source:
    owner: cloudfoundry-incubator
    repository: kubo-deployment
    access_token: ((github-access-token))
- name: prometheus-operator
  type: github-release
  check_every: 30m
  source:
    owner: coreos
    repository: prometheus-operator
    access_token: ((github-access-token))
- name: spring-boot
  type: maven
  check_every: 30m
  source:
    url: https://repo1.maven.org/maven2
    artifact: org.springframework.boot:spring-boot-dependencies:pom
- name: spring-cloud
  type: maven
  check_every: 30m
  source:
    url: https://repo1.maven.org/maven2
    artifact: org.springframework.cloud:spring-cloud-dependencies:pom
- name: spring-cloud-milestone
  type: maven
  check_every: 30m
  source:
    url: https://repo.spring.io/milestone
    artifact: org.springframework.cloud:spring-cloud-dependencies:pom

jobs:
# GitHub Release => GitHub issue
- name: check-concourse-version
  plan:
  - aggregate:
    - get: release
      resource: concourse
      trigger: true
      params:
        globs:
        - fly_linux_amd64
    - get: ci-utils
  - task: generate-gh-issue
    params:
      ISSUE_USER: making-bot
      ISSUE_COMPONENT: concourse/concourse
      ISSUE_REPO: making/kanban
      GITHUB_API_TOKEN:  ((github-access-token))
    file: ci-utils/tasks/generate-gh-issue.yml 

- name: check-cfcr-version
  plan:
  - aggregate:
    - get: release
      resource: cfcr
      trigger: true
    - get: ci-utils
  - task: generate-gh-issue
    params:
      ISSUE_USER: making-bot
      ISSUE_COMPONENT: cloudfoundry-incubator/kubo-deployment
      ISSUE_REPO: making/kanban
      GITHUB_API_TOKEN:  ((github-access-token))
    file: ci-utils/tasks/generate-gh-issue.yml 

- name: check-prometheus-operator-version
  plan:
  - aggregate:
    - get: release
      resource: prometheus-operator
      trigger: true
    - get: ci-utils
  - task: generate-gh-issue
    params:
      ISSUE_USER: making-bot
      ISSUE_COMPONENT: coreos/prometheus-operator
      ISSUE_REPO: making/kanban
      GITHUB_API_TOKEN:  ((github-access-token))
    file: ci-utils/tasks/generate-gh-issue.yml 

# Maven => GitHub issue
- name: check-spring-boot-version
  plan:
  - aggregate:
    - get: pom
      resource: spring-boot
      trigger: true
    - get: ci-utils
  - task: generate-version
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      inputs:
      - name: pom
      outputs:
      - name: release
      run:
        path: bash
        args: 
        - -c
        - |
          set -e
          ls pom/*.pom | sed 's|pom/spring-boot-dependencies-||' | sed 's|.pom||' > ./release/version
  - task: generate-gh-issue
    params:
      ISSUE_USER: making-bot
      ISSUE_COMPONENT: spring-projects/spring-boot
      ISSUE_REPO: making/kanban
      GITHUB_API_TOKEN:  ((github-access-token))
    file: ci-utils/tasks/generate-gh-issue.yml 

- name: check-spring-cloud-version
  plan:
  - aggregate:
    - get: pom
      resource: spring-cloud
      trigger: true
    - get: ci-utils
  - task: generate-version
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      inputs:
      - name: pom
      outputs:
      - name: release
      run:
        path: bash
        args: 
        - -c
        - |
          set -e
          ls pom/*.pom | sed 's|pom/spring-cloud-dependencies-||' | sed 's|.pom||' > ./release/version
  - task: generate-gh-issue
    params:
      ISSUE_USER: making-bot
      ISSUE_COMPONENT: spring-cloud/spring-cloud-build
      ISSUE_REPO: making/kanban
      GITHUB_API_TOKEN:  ((github-access-token))
    file: ci-utils/tasks/generate-gh-issue.yml 

- name: check-spring-cloud-version-milestone
  plan:
  - aggregate:
    - get: pom
      resource: spring-cloud-milestone
      trigger: true
    - get: ci-utils
  - task: generate-version
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      inputs:
      - name: pom
      outputs:
      - name: release
      run:
        path: bash
        args: 
        - -c
        - |
          set -e
          ls pom/*.pom | sed 's|pom/spring-cloud-dependencies-||' | sed 's|.pom||' > ./release/version
  - task: generate-gh-issue
    params:
      ISSUE_USER: making-bot
      ISSUE_COMPONENT: spring-cloud/spring-cloud-build
      ISSUE_REPO: making/kanban
      GITHUB_API_TOKEN:  ((github-access-token))
    file: ci-utils/tasks/generate-gh-issue.yml 

# GitHub Release => Pivotal Tacker Story
# - name: check-concourse-version-for-tracker
#   plan:
#   - aggregate:
#     - get: release
#       resource: concourse
#       trigger: true
#       params:
#         globs:
#         - fly_linux_amd64
#     - get: ci-utils
#   - task: generate-pivotal-tracker-story
#     params:
#       ISSUE_COMPONENT: concourse/concourse
#       PIVOTAL_TRACKER_PROJECT_ID: ((pivotal-tracker-project-id))
#       PIVOTAL_TRACKER_TOKEN: ((pivotal-tracker-token))
#     file: ci-utils/tasks/generate-pivotal-tracker-story.yml 